# Generated by Django 3.2.5 on 2021-07-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_registration_status',
            field=models.CharField(choices=[('O', 'open'), ('c', 'closed')], default='O', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('U', 'upcomming'), ('C', 'completed')], default='U', max_length=2),
        ),
    ]
