# Generated by Django 3.2.5 on 2021-07-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_auto_20210715_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_registration_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('upcomming', 'upcomming'), ('completed', 'completed')], default='upcomming', max_length=12),
        ),
    ]
