# Generated by Django 3.2.5 on 2021-07-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_auto_20210715_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_registration_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('notopen', 'notopen ')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='Look_and_feel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='home')),
                ('ad_image', models.ImageField(upload_to='home')),
                ('about_events_now', models.TextField()),
                ('quote_events_now', models.CharField(max_length=200)),
                ('promo_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.event')),
            ],
            options={
                'db_table': 'Events_Now',
            },
        ),
    ]
