# Generated by Django 3.2.5 on 2021-07-15 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_auto_20210715_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='look_and_feel',
            name='active_status',
            field=models.CharField(choices=[('c', 'current'), ('o', 'off')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='look_and_feel',
            name='promo_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event_management.event'),
        ),
    ]
