# Generated by Django 3.2.5 on 2021-07-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_auto_20210715_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='look_and_feel',
            name='ad_image',
        ),
    ]
