# Generated by Django 3.2.5 on 2021-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_alter_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_registration_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('notopen', 'notopen ')], default='open', max_length=10),
        ),
    ]
