# Generated by Django 3.2.5 on 2021-07-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0009_competition_competition_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_date',
            field=models.DateTimeField(),
        ),
    ]
