# Generated by Django 3.2.5 on 2021-07-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0010_alter_competition_competition_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='look_and_feel',
            table='Herald Event Manager',
        ),
    ]
